# Generated by Django 2.2.15 on 2020-08-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('HO', 'host'), ('GU', 'guest')], default='HO', max_length=5),
        ),
    ]
