# Generated by Django 2.2.15 on 2020-08-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200820_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
