# Generated by Django 2.2.15 on 2020-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='try_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
